export const EVENT = {
  brideName: 'Sakshi',
  groomName: 'Jayant',
  brideFull: 'Sakshi Rastogi',
  groomFull: 'Jayant Patel',
  brideParents: 'Shri Vipin Rastogi & Smt. Ragni Rastogi',
  groomParents: 'Er. Adarsh Patel & Smt. Urmila Patel',
  date: new Date('2026-11-14T19:00:00'),
  dateLabel: 'Saturday, 14 November',
  yearLabel: '2026',
  time: '7:00 PM',
  venueName: 'Lemon Tree Hotel',
  venueAddress: 'EDM Mall, Kaushami, Ghaziabad',
  mapUrl: 'https://maps.app.goo.gl/SdAf2BoZhx381Er57?g_st=ic',
  rsvpDeadline: 'November 1, 2026',
  hashtag: '#JayantAndSakshi',
  rsvpWhatsappNumber: '919540214384',
  rsvpContactName: 'Sakshi Rastogi',
};
